github:
  is_project_page: false

theme: jekyll-theme-hacker

  # Site wide configuration

title: Joakim Argillander Projects Page
locale: sv_SE
logo: # filename of a logo image that has been placed into your images directory


# Google Analytics
google_analytics: UA-48162518-4


owner:
  name: Joakim Argillander
  email: joakim@argillander.se