github:
  is_project_page: false

theme: jekyll-theme-hacker

  # Site wide configuration

title: Joakim Argillander Projects Page
locale: sv_SE
logo: # filename of a logo image that has been placed into your images directory

owner:
  name: Joakim Argillander
  email: joakim@argillander.se